version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nock
    versions:
    - 13.0.5
    - 13.0.7
    - 13.0.9
  - dependency-name: pino-pretty
    versions:
    - 4.3.0
    - 4.5.0
  - dependency-name: qs
    versions:
    - 6.9.4
    - 6.9.6
  - dependency-name: "@types/pino"
    versions:
    - 6.3.4
    - 6.3.5
  - dependency-name: tape
    versions:
    - 5.1.0
    - 5.1.1
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: agentkeepalive
    versions:
    - 4.1.3
