name: release
on: [ release ]
jobs:
  build_binary:
    name: build-binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn bundle
    - run: yarn binary
    - run: chmod -R ugo+x websight-*
    - uses: JasonEtco/upload-to-release@master
      name: upload-linux-binary
      with:
        args: 'websight-linux-x64 application/x-executable'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      name: upload-macOS-binary
      with:
        args: 'websight-darwin-x64 application/x-mach-binary'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      name: upload-windows-binary
      with:
        args: 'websight-windows-x64 application/vnd.microsoft.portable-executable'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
